# Please NOTE: In this sample we're assuming Cloud Api Server is hosted at "https://localhost". 
# If it's not then please replace this with with your hosting url.

curl --location --request PUT '<insert presignedUrl generated by https://localhost/file/upload/get-presigned-url >' \
--header 'x-api-key: {{x-api-key}}' \
--form 'file=@/Users/em/Downloads/logo.png'