//*******************************************************************************************//
//                                                                                           //
// Download Free Evaluation Version From: https://bytescout.com/download/web-installer       //
//                                                                                           //
// Also available as Web API! Get Your Free API Key: https://app.pdf.co/signup               //
//                                                                                           //
// Copyright © 2017-2020 ByteScout, Inc. All rights reserved.                                //
// https://www.bytescout.com                                                                 //
// https://pdf.co                                                                            //
//                                                                                           //
//*******************************************************************************************//


using System;
using RestSharp;
namespace HelloWorldApplication {
	// Please NOTE: In this sample we're assuming Cloud Api Server is hosted at "https://localhost". 
	// If it's not then please replace this with with your hosting url.
		class HelloWorld {
				static void Main(string[] args) {
						var client = new RestClient("<insert presignedUrl generated by https://localhost/file/upload/get-presigned-url >");
						client.Timeout = -1;
						var request = new RestRequest(Method.PUT);
						request.AddHeader("x-api-key", "{{x-api-key}}");
						request.AddFile("file", "/Users/em/Downloads/logo.png");
						IRestResponse response = client.Execute(request);
						Console.WriteLine(response.Content);
				}
		}
}
