'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



''' <summary>
''' _Default class.
''' </summary>
''' <remarks>
''' Auto-generated class.
''' </remarks>
Public Partial Class _Default

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' FileUpload1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

	''' <summary>
	''' UploadButton control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected UploadButton As Global.System.Web.UI.WebControls.Button

	''' <summary>
	''' UploadStatusLabel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected UploadStatusLabel As Global.System.Web.UI.WebControls.Label

	''' <summary>
	''' ListBox1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ListBox1 As Global.System.Web.UI.WebControls.ListBox
End Class
