/*
 * bytescout.io
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-05-11T04:47:23Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bytescout.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * PdfSignRequestModelImages
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-11T14:49:35.132Z")
public class PdfSignRequestModelImages {
  @SerializedName("url")
  private String url = null;

  @SerializedName("x")
  private BigDecimal x = null;

  @SerializedName("y")
  private BigDecimal y = null;

  @SerializedName("width")
  private BigDecimal width = null;

  @SerializedName("height")
  private BigDecimal height = null;

  @SerializedName("pages")
  private String pages = null;

  public PdfSignRequestModelImages url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL of the signature image
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "URL of the signature image")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public PdfSignRequestModelImages x(BigDecimal x) {
    this.x = x;
    return this;
  }

   /**
   * X coordinate of the signature in PDF Points (1/72 in.)
   * @return x
  **/
  @ApiModelProperty(example = "null", value = "X coordinate of the signature in PDF Points (1/72 in.)")
  public BigDecimal getX() {
    return x;
  }

  public void setX(BigDecimal x) {
    this.x = x;
  }

  public PdfSignRequestModelImages y(BigDecimal y) {
    this.y = y;
    return this;
  }

   /**
   * Y coordinate of the signature in PDF Points (1/72 in.)
   * @return y
  **/
  @ApiModelProperty(example = "null", value = "Y coordinate of the signature in PDF Points (1/72 in.)")
  public BigDecimal getY() {
    return y;
  }

  public void setY(BigDecimal y) {
    this.y = y;
  }

  public PdfSignRequestModelImages width(BigDecimal width) {
    this.width = width;
    return this;
  }

   /**
   * Width of the signature in PDF Points (1/72 in.)
   * @return width
  **/
  @ApiModelProperty(example = "null", value = "Width of the signature in PDF Points (1/72 in.)")
  public BigDecimal getWidth() {
    return width;
  }

  public void setWidth(BigDecimal width) {
    this.width = width;
  }

  public PdfSignRequestModelImages height(BigDecimal height) {
    this.height = height;
    return this;
  }

   /**
   * Height of the signature in PDF Points (1/72 in.)
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "Height of the signature in PDF Points (1/72 in.)")
  public BigDecimal getHeight() {
    return height;
  }

  public void setHeight(BigDecimal height) {
    this.height = height;
  }

  public PdfSignRequestModelImages pages(String pages) {
    this.pages = pages;
    return this;
  }

   /**
   * Comma-separated list of page indices (or ranges) to process. Leave empty for all pages. Example: '0,2-5,7-'.
   * @return pages
  **/
  @ApiModelProperty(example = "null", value = "Comma-separated list of page indices (or ranges) to process. Leave empty for all pages. Example: '0,2-5,7-'.")
  public String getPages() {
    return pages;
  }

  public void setPages(String pages) {
    this.pages = pages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfSignRequestModelImages pdfSignRequestModelImages = (PdfSignRequestModelImages) o;
    return Objects.equals(this.url, pdfSignRequestModelImages.url) &&
        Objects.equals(this.x, pdfSignRequestModelImages.x) &&
        Objects.equals(this.y, pdfSignRequestModelImages.y) &&
        Objects.equals(this.width, pdfSignRequestModelImages.width) &&
        Objects.equals(this.height, pdfSignRequestModelImages.height) &&
        Objects.equals(this.pages, pdfSignRequestModelImages.pages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, x, y, width, height, pages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfSignRequestModelImages {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    pages: ").append(toIndentedString(pages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

