<?php
/**
 * BarCodeSizeVm
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bytescout\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Bytescout\Client\Model;

use \ArrayAccess;
/**
 * BarCodeSizeVm Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Bytescout\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BarCodeSizeVm implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'height' => 'float',
        'width' => 'float',
        'unitOfMeasure' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'height' => 'height',
        'width' => 'width',
        'unitOfMeasure' => 'unitOfMeasure'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'height' => 'setHeight',
        'width' => 'setWidth',
        'unitOfMeasure' => 'setUnitOfMeasure'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'height' => 'getHeight',
        'width' => 'getWidth',
        'unitOfMeasure' => 'getUnitOfMeasure'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $height Height of area
      * @var float
      */
    protected $height;
    
    /**
      * $width Width of area
      * @var float
      */
    protected $width;
    
    /**
      * $unitOfMeasure Unit of measure.\r\n            Default value: Pixel
      * @var string
      */
    protected $unitOfMeasure;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->height = $data["height"];
            $this->width = $data["width"];
            $this->unitOfMeasure = $data["unitOfMeasure"];
        }
    }
    
    /**
     * Gets height
     * @return float
     */
    public function getHeight()
    {
        return $this->height;
    }
  
    /**
     * Sets height
     * @param float $height Height of area
     * @return $this
     */
    public function setHeight($height)
    {
        
        $this->height = $height;
        return $this;
    }
    
    /**
     * Gets width
     * @return float
     */
    public function getWidth()
    {
        return $this->width;
    }
  
    /**
     * Sets width
     * @param float $width Width of area
     * @return $this
     */
    public function setWidth($width)
    {
        
        $this->width = $width;
        return $this;
    }
    
    /**
     * Gets unitOfMeasure
     * @return string
     */
    public function getUnitOfMeasure()
    {
        return $this->unitOfMeasure;
    }
  
    /**
     * Sets unitOfMeasure
     * @param string $unitOfMeasure Unit of measure.\r\n            Default value: Pixel
     * @return $this
     */
    public function setUnitOfMeasure($unitOfMeasure)
    {
        $allowed_values = array("pixel", "point", "inch", "document", "millimeter", "centimeter", "twip");
        if (!in_array($unitOfMeasure, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'unitOfMeasure', must be one of 'pixel', 'point', 'inch', 'document', 'millimeter', 'centimeter', 'twip'");
        }
        $this->unitOfMeasure = $unitOfMeasure;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Bytescout\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Bytescout\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
