'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits Global.System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = DirectCast(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property LastUsedFolder() As String
			Get
				Return DirectCast(Me("LastUsedFolder"), String)
			End Get
			Set
				Me("LastUsedFolder") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property LastUsedFolder2() As String
			Get
				Return DirectCast(Me("LastUsedFolder2"), String)
			End Get
			Set
				Me("LastUsedFolder2") = value
			End Set
		End Property
	End Class
End Namespace
